# Generated by Django 2.1.5 on 2020-05-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('type_education', models.CharField(choices=[('w', 'Workshop'), ('c', 'Course'), ('u', 'University'), ('t', 'Training')], default='t', max_length=1)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_experience', models.CharField(choices=[('c', 'Company'), ('p', 'Project')], default='c', max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('date', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('icon', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='aboutMe.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='aboutMe.Skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='aboutMe.Profile'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='aboutMe.Profile'),
        ),
    ]
