# Generated by Django 2.1.5 on 2019-08-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0002_experience'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together={('user',)},
        ),
    ]
