# Generated by Django 2.1.5 on 2020-05-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0006_auto_20200510_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('type_education', models.CharField(choices=[('w', 'Workshop'), ('c', 'Course'), ('u', 'University'), ('t', 'Training')], max_length=1)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='aboutMe.Profile')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='aboutMe.Skill'),
        ),
        migrations.AddField(
            model_name='experience',
            name='type_experience',
            field=models.CharField(choices=[('c', 'Company'), ('p', 'Project')], default=456, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='user',
            field=models.ForeignKey(default=456, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='aboutMe.Profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
