# Generated by Django 2.1.5 on 2020-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200506_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
        migrations.AddField(
            model_name='categories',
            name='nameUrl',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
