# Generated by Django 2.1.5 on 2020-05-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200506_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='nameUrl',
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=123, unique=True),
            preserve_default=False,
        ),
    ]
