# Generated by Django 2.1.5 on 2020-05-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200506_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='nameUrl',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categories'),
        ),
    ]
